name: Django CI

on:
  push:
    branches: [ master, wild, ci ]
  pull_request:
    branches: [ master, wild, ci ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Poetry
      run: |
        pip install --user poetry
    - name: Set up Coveralls
      run: |
        pip install coveralls pyyaml
    - name: Install Dependencies
      run: |
        script/bootstrap
    - name: Run Tests
      run: |
        script/cibuild
    - name: Upload coverage report
      run: |
        coveralls --service=github
